Add `UnknownCSI` event type
redox-os/termion pull request #73
Opened 2016-11-08 22:23 UTC by gyscos

When a CSI sequence is not parsed by termion, return a special `UnknownCSI` event including the byte sequence, allowing applications using termion to do their own parsing.

2016-11-10 23:40 UTC, gyscos commented
The price to pay for that is that `Copy` can no longer be derived for `Event`, since it could contain a `Vec<u8>` - this means it breaks backward-compatibility.
An alternative would be to use a fixed-size buffer like `[u8; 8]` to hold the content, but I'm not sure it'd be a better solution.

2016-12-14 20:51 UTC, gyscos commented
Possible bikeshedding: should we include the CSI prefix in the returned bytes?

2016-12-16 15:31 UTC, ticki commented
I think it's fine. As soon as my comment is fixed, I'll merge :)

2016-12-16 15:31 UTC, ticki requested changes

2016-12-16 15:31 UTC, ticki commented on src/event.rs
> +    UnknownCSI(Vec<u8>),
It should be `UnknownCsi` per the Rust naming convention.

2016-12-16 15:32 UTC, ticki commented
The new review system on GitHub is cool.

2016-12-16 16:47 UTC, gyscos commented
Renamed

2016-12-16 17:20 UTC, ticki commented
:+1:

2016-12-16 17:20 UTC, merged