Add support for alternate screen
redox-os/termion pull request #88
Opened 2017-02-18 12:17 UTC by ftilde

I went ahead and reimplemented the screen switching escape codes introduced in #66, but followed the suggestions of @jackpot51 and implemented a separate wrapper struct `AlternateScreen`.

Additionally I added two types `ToAlternateScreen` and `ToMainScreen` that can be used directly to switch between screens manually.

This addresses issue #77.

2017-02-18 17:26 UTC, ticki commented
Very interesting. I'll check it out in one of the coming days.

If you hear no response from me, please ping me.

2017-02-25 19:21 UTC, ticki requested changes
This is pretty damn cool. I left a few nitpicky comments.

When they're fixed, it's ready for merging.

2017-02-25 19:21 UTC, ticki commented on src/screen.rs
> +//! Managing switching between main and alternate screen buffers
Needs `.`.

2017-02-25 19:21 UTC, ticki commented on src/screen.rs
> +/// Switch to the alternate screen buffer of the terminal
Here too.

2017-02-25 19:21 UTC, ticki commented on src/screen.rs
> +    output: W,
I know this is extremely nitpicky, but could you add a comment like

```
/// The output target.
```

to this even though it's private?

It slightly improves the docs when private item rendering is enabled.

2017-02-27 12:26 UTC, ftilde commented
I improved the documentation as you suggested.

2017-02-27 12:42 UTC, ticki commented
Very nice!

2017-02-27 12:42 UTC, merged