Added color support detection
redox-os/termion pull request #91
Opened 2017-02-22 20:58 UTC by IGI-111

This is meant at least as a partial answer to #78.

Color support is inferred by using either `OSC 4` escape codes or the value of `TERM`.
It can't detect what the terminal isn't advertising, so in certain cases, it's possible the terminal supports more colors but doesn't say.

One thing to discuss might be the the value of the timeout for answers, although 100ms works well in practice.

2017-02-25 19:16 UTC, ticki commented
Even though this is just 88 lines, this is actually really cool. Very nice work.

I left some comments. Don't worry about the `</nitpick>` ones, I'll take care of those.

2017-02-25 19:17 UTC, ticki requested changes
I left some comments. Don't worry about the </nitpick> ones, I'll take care of those.

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +pub trait DetectColors {
Why not integrate this directly into `RawTerminal`?

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +/// Types that allow detection of the colors they support
Needs `.`

</nitpick>

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +            // OSC 4 is supported, detect how many colors there are
Needs `.`

</nitpick>

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +            while min + 1 < max {
While it is somewhat obvious what happens here, it could need a small explanatory comment.

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +            // OSC 4 is not supported, trust TERM contents
Needs `.`

</nitpick>

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +/// Detect a color using OSC 4
Needs `.`

</nitpick>

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +    let timeout = Duration::from_millis(100);
`100` should be a `const`, not hard-coded.

2017-02-25 19:17 UTC, ticki commented on src/color.rs
> +    write!(stdout, "\x1B]4;{};?\x07", color)?;
All this is a bit confusing. Perhaps add a comment or two here.

2017-02-26 00:37 UTC, IGI-111 commented on src/color.rs
> +pub trait DetectColors {
Well given #88 and the possibility of having other `Write`able interfaces that are raw, I thought a Trait made more sense.

It's also very color related so it felt more correct to have it as an optional thing you can include from the `color` module.

2017-02-26 08:35 UTC, ticki commented on src/color.rs
> +pub trait DetectColors {
ah ok

2017-02-26 08:35 UTC, merged